//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerseusApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerseusApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;crosslinks xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///   &lt;crosslink title=&quot;DSS&quot; description=&quot;Disuccinimidyl suberate&quot; create_date=&quot;2012-07-22T19:30:51.122051+02:00&quot; last_modified_date=&quot;2015-09-06T23:34:46.8422502+02:00&quot; user=&quot;cox&quot; saturated_composition=&quot;H(10) C(8) O(2)&quot; unsaturated_composition=&quot;H(12) C(8) O(3)&quot; specificity=&quot;K&quot; proteinNterm=&quot;true&quot; proteinCterm=&quot;false&quot;&gt;
        ///      &lt;position&gt;notTerm&lt;/position&gt;
        ///   &lt;/cros [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string crosslinks {
            get {
                return ResourceManager.GetString("crosslinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;databases xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;database create_date=&quot;2015-08-20T07:43:29.1637021+02:00&quot; last_modified_date=&quot;2015-06-26T07:44:08.7480425+02:00&quot; user=&quot;cox&quot; filename=&quot;UP000029777_1241371.fasta&quot; identifier_parse_rule=&quot;&amp;gt;.*\|(.*)\|&quot; description_parse_rule=&quot;&quot; taxonomy_parse_rule=&quot;&quot; variation_parse_rule=&quot;&quot; modification_parse_rule=&quot;&quot; species=&quot;Abalone herpesvirus Victoria/AUS/2009&quot; taxid=&quot;124137 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string databases {
            get {
                return ResourceManager.GetString("databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;enzymes xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///   &lt;enzyme title=&quot;Trypsin&quot; description=&quot;Cleaves after lysine and arginine but not before proline&quot; create_date=&quot;2012-08-02T13:11:29.3998419+02:00&quot; last_modified_date=&quot;2012-08-02T13:12:00.0850958+02:00&quot; user=&quot;cox&quot;&gt;
        ///      &lt;specificity&gt;
        ///         &lt;string&gt;RA&lt;/string&gt;
        ///         &lt;string&gt;RR&lt;/string&gt;
        ///         &lt;string&gt;RN&lt;/string&gt;
        ///         &lt;string&gt;RD&lt;/string&gt;
        ///         &lt;strin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enzymes {
            get {
                return ResourceManager.GetString("enzymes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;modifications xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///   &lt;modification title=&quot;Acetyl (K)&quot; description=&quot;Acetylation&quot; create_date=&quot;2010-01-19T13:25:24.82357+01:00&quot; last_modified_date=&quot;2010-01-19T14:15:40.2445414+01:00&quot; user=&quot;neuhause&quot; reporterCorrectionM2=&quot;0&quot; reporterCorrectionM1=&quot;0&quot; reporterCorrectionP1=&quot;0&quot; reporterCorrectionP2=&quot;0&quot; reporterCorrectionType=&quot;false&quot; composition=&quot;C(2) H(2) O&quot;&gt;
        ///      &lt;position&gt;notCt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modifications {
            get {
                return ResourceManager.GetString("modifications", resourceCulture);
            }
        }
    }
}
